### ISSUE TITLE
No delimiter in string, cannot determine type Error

### ISSUE THREAD

**Issue by yepp4you** [EOSIO/eosjs-ecc#11]
It seems that the signature has changed in eos. 
It seems that we need to make changes.
libraries/fc/src/crypto/signature.cpp
   static signature::storage_type parse_base58(const std::string& base58str)
   {
      constexpr auto prefix = config::signature_base_prefix;

      const auto pivot = base58str.find('_');
      FC_ASSERT(pivot != std::string::npos, "No delimiter in string, cannot determine type: ${str}", ("str", base58str));

      const auto prefix_str = base58str.substr(0, pivot);
      FC_ASSERT(prefix == prefix_str, "Signature Key has invalid prefix: ${str}", ("str", base58str)("prefix_str", prefix_str));

      auto data_str = base58str.substr(pivot + 1);
      FC_ASSERT(!data_str.empty(), "Signature has no data: ${str}", ("str", base58str));
      return base58_str_parser<signature::storage_type, config::signature_prefix>::apply(data_str);
   }

Error Log ==> 
https://github.com/EOSIO/eos/commit/f55f431f8fb4d91e8d872d281ffd3a1cd9de3758#diff-41a221719ab6bb16c1ddaf8a235c9a47

**Comment by jcalfee** [comment]
The signature error is fixed and published under: eosjs@10.0.0 (also eosjs@dawn3) ..

**Comment by BinaryFocus** [comment]
I've just tested this and it seems to be working. Thank you!

**Comment by nsjames** [comment]
They must be driving you crazy James :)

**Comment by crypto5000** [comment]
Confirmed. Now works for me, too. James is a rock star with these turnarounds.

**Comment by jcalfee** [comment]
The other changes are moved to this ticket: https://github.com/EOSIO/eosjs-ecc/issues/12
