### ISSUE TITLE
When developing a web wallet, how do you combine eosjs-ecc with eosjs to complete the signature verification process of the transaction?

### ISSUE THREAD

**Issue by songsongMr** [EOSIO/eosjs-ecc#13]

**Comment by jcalfee** [comment]
eosjs-ecc is already included in eosjs .. You'll probaby see an example that does what you want in the [README](https://github.com/EOSIO/eosjs/blob/master/README.md)..

The only reason why you want eosjs-ecc alone is if you only want to work with private keys offline..

**Comment by songsongMr** [comment]
what the Application scenarios of the sign of eosjs-ecc .

**Comment by songsongMr** [comment]
Using an account to initiate a request to eos,, it seems that eos is just to check whether his private key is in keyProvider, if in the request is successful. What is the use of signatures in ecc?

**Comment by jcalfee** [comment]
Signatures are used anytime your writing data to the blockchain..    Reading data is public and does not need any private key or signature.

**Comment by songsongMr** [comment]
I'm not sure if my understanding of the signature is correct.I hope to get your advice. Could you show me an example . Thank you so much!
eos.transaction({
          actions: [
            {
              account: 'tester',
              name: 'reguser',
              authorization: [{
                actor: 'tester',
                permission: 'active'
              }], //Is this the signature? it will get the key from keyProvider. if the key is in keyProvider, the process of  signature is complete.I'm not sure if my understanding of the signature is correct.I hope to get your advice.
              data: {
                name: "test",
                wname: "w123",
                password: "12345",               
                memo:"call reguser"
              }
            }
          ]
        })

**Comment by jcalfee** [comment]
Is there a reason your using eos.transaction?  Can you instead pull the contract and call reguser directly?

Never put a password in a transaction like this.. It will be instantly seen by the entire network..  You'll probably need to change this to use public key private key security..
```js
eos.contract('tester').then(tester => {
    tester.reguser({
        name: "test",
        wname: "w123",
        memo:"call reguser"
    })
})

```

**Comment by goldenfiredo** [comment]
would you please show how to work with private key offline with eosjs-ecc? Thanks.

**Comment by jcalfee** [comment]
Anywhere you see `wif` in the README that is working with a private key in the API .. Do you have a more specific question?

**Comment by jcalfee** [comment]
All method calls are "offline" .. there are no network API requests in this package.

**Comment by sehgal12** [comment]
@jcalfee  Hi, One of the action in my smart contract require multiple permission(from user and admin). Can you suggest me the way to get the transaction signed by the user, receive it and sign it by admin and finally push to the blockchain?

**Comment by jcalfee** [comment]
The keyprovider is an array of private keys only .. See the README here: https://github.com/EOSIO/eosjs

**Comment by frankli1224** [comment]
@jcalfee ,Thank you! I will read the readme file. Thank you!

**Comment by frankli1224** [comment]
@jcalfee , Hello again! I found this in readme file

"keyProvider [array<string>|string|function]"  

I wonder how to write the "array<string>" for private keys, because I have give two private keys in the key provider, one for active key one for owner key

**Comment by jcalfee** [comment]
`keyProvider = ['5KELKQohNbdoJ2MRmHPQh6ef7tFWSpBQ1gCpcjkNKER7hWczwCZ', '5J38vcyy1CVR9NeAArrZfeAUzjyGEAzJZmJ7paLHqJYKQo6hQC9']`
