### ISSUE TITLE
Is there support RN package to use?

### ISSUE THREAD

**Issue by xntop** [EOSIO/eosjs-ecc#15]
Is there support RN package to use?

**Comment by jcalfee** [comment]
RN package?

**Comment by xntop** [comment]
@jcalfee yea, react native lib.

**Comment by jcalfee** [comment]
Lol .. guess I answered that question.  I don't have a RN package.  Eosjs-ecc should work though, it does not use local storage or any window or document objects.  Have you tried it?

**Comment by xntop** [comment]
@jcalfee I have tried it and it works well， thanks
