### ISSUE TITLE
the aes api is not easy to use, consider to enhance it ?

### ISSUE THREAD

**Issue by crazybits** [EOSIO/eosjs-ecc#23]
too much infor is required for existing aes api ,can we enhance to something like:

> cipher_text =encrypt(password,plain_text)
> plain_text= decrpt(password,cipher_text)
>

**Comment by jcalfee** [comment]
I probably need to deprecate these.  They use to be used for memo encryption but we don't have support for this in nodeos ..  Until we have a usage and a standard I can't say that these will stick around.

**Comment by crazybits** [comment]
@jcalfee  thanks for the infor, i am using crypto-js now as a alternative to encrypt and decrypt the private key
