### ISSUE TITLE
Can I convert signature string (SIG_K1_...) to eos signature struct(uint8)

### ISSUE THREAD

**Issue by jacktang** [EOSIO/eosjs-ecc#35]
Hello,

I generate the signature using `ecc.Signature.signHash(sha256hash, privateKey).toString()` and how can I convert to eos signature struct?

P.S:
```
struct signature {
   uint8_t data[66];
};
```

**Comment by jacktang** [comment]
well, i got the answer now so that close it.

**Comment by shwuhk** [comment]
@jacktang May I know how did you do that finally?

**Comment by WhaleEx** [comment]
@jacktang May I know how did you do that finally?
