### ISSUE TITLE
the multiplyTwo 's Inverse operation

### ISSUE THREAD

**Issue by free-snail** [EOSIO/eosjs-ecc#42]
var Q = R.multiplyTwo(s, G, eNeg)

If i know the Q,R,S,G value  how can i get the eNeg value?

**Comment by liyun2060** [comment]
and what's mean is multiplyTwo
R.multiplyTwo(s, G, eNeg) = r*s +G*eNeg
but R and G  struct as
(100000000000000000,1000000000000000)

**Comment by liyun2060** [comment]
I know it. But how the multiply function  's  Inverse
