### ISSUE TITLE
npm run build does not build eosjs-ecc.js

### ISSUE THREAD

**Issue by angelol** [EOSIO/eosjs-ecc#6]
Output of npm run build:

----
Angelos-iMac:eosjs-ecc al$ npm run build

> eosjs-ecc@3.0.2 build /Users/al/Documents/eos-encryption-demo/eosjs-ecc
> babel src --out-dir lib

src/aes.js -> lib/aes.js
src/api_common.js -> lib/api_common.js
src/api_object.js -> lib/api_object.js
src/common.test.js -> lib/common.test.js
src/config.js -> lib/config.js
src/ecdsa.js -> lib/ecdsa.js
src/ecsignature.js -> lib/ecsignature.js
src/enforce_types.js -> lib/enforce_types.js
src/hash.js -> lib/hash.js
src/index.js -> lib/index.js
src/key_private.js -> lib/key_private.js
src/key_public.js -> lib/key_public.js
src/key_utils.js -> lib/key_utils.js
src/object.test.js -> lib/object.test.js
src/promise-async.js -> lib/promise-async.js
src/signature.js -> lib/signature.js

----

Seems to be running without error but then, contrary to the readme, there is no eosjs-ecc.js file to be found.

**Comment by jcalfee** [comment]
The target is: `npm run build_browser`

Is there any reason to have that in "build" ?  I did not include it in the main build because when this package is included in another npm project this library is not used, only the files in the lib directory.

**Comment by angelol** [comment]
Thanks, Jcalfee. But in the Readme it says:

# Browser

```bash
git clone https://github.com/EOSIO/eosjs-ecc.git
cd eosjs-ecc
npm install
npm run build
# builds: ./dist/eosjs-ecc.js
# Verify release hash
```

That means the readme needs to be updated, no?

**Comment by jcalfee** [comment]
fixed, thank you

**Comment by duyluong1994** [comment]
Hi, i'm having this issue when using eosjs-ecc with angular (ng build doesnt build eosjs-ecc to dist).
