### ISSUE TITLE
correct HDWallet derivation path for EOS keys

### ISSUE THREAD

**Issue by seita-uc** [EOSIO/eosjs-ecc#7]
I would like to know the correct derivation path in order to derive EOS keys from mnemonic phrases. Now I am referring to [SatoshiLab](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)'s list of coin types for BIP44. Please let me know if it is wrong.

**Comment by seita-uc** [comment]
I really appreciate your detailed explanation. This is of great help to me :)

**Comment by seita-uc** [comment]
I got one more question: In which level of private key is recommended to use as standard? For example, which level is used at [generate EOS keys](https://eos.io/instructions) in eos.io?

**Comment by jcalfee** [comment]
Generate EOS Key at eos.io is non-deterministic (completely random).

@dskvr can you please update us on how a EOS claim will happen (does this still need an account name for example)?

You can probably setup a deterministic claim key by using a MASTER_SALT that includes the chain ID concatenated with some words 'EOS Claim Key' and something else to make the claim key unique for the user for each ETH account they are claiming (so the ETH address):
```js
MASTER_SALT = chainId + 'EOS Claim Key' + ethAddress
```

The chainCode / MASTER_SALT will probably be a hash of the genesis block (all the initial balances, etc).  It will not be available until the chain is live.

**Comment by jcalfee** [comment]
For "Generate EOS Key" aka (EOS Claim Key), normalization is as follows:
* chainId (all lowercase hex string)
* 'EOS Claim Key' case sensitive string concatenation
* ethAddress - Validate the ETH Address ensuring it starts with `0x` and that the [checksum matches](https://github.com/ethereum/EIPs/issues/55).  If the address is valid, use this as the 3rd and final concatenation and proceed with the MASTER_SALT.  If the ETH Address is not valid but appears to be a valid address (the right length and character set), an attempt to fix the address may be offered.  Warn and prompt the user that this ETH Address could not be validated and ask to proceed anyways.  The software should then convert the ETH Address into its mix-case format and ensure a `0x` prefix exists or is added then concat the mix cased format as a string to create the MASTER_SALT.

**Comment by seita-uc** [comment]
Thanks to your help, I could successfully derived my eos pub/priv key from my mnemonic 👍.
Thank you very much!

**Comment by dengzz** [comment]
could use this one for EOS keys?
`
const hdkey = require('hdkey')
const wif = require('wif')
const ecc = require('eosjs-ecc')
const assert = require('assert')
const bip39 = require('bip39')
const mnemonic = 'real flame win provide layer trigger soda erode upset rate beef wrist fame design merit'
const seed = bip39.mnemonicToSeedHex(mnemonic)
const master = hdkey.fromMasterSeed(Buffer(seed, 'hex'))
const node =  master.derive("m/44'/194'/0'/0/0")
console.log("publicKey: "+ecc.PublicKey(node._publicKey).toString())
console.log("privateKey: "+wif.encode(128, node._privateKey, false))
`
result:
publicKey: EOS61oRAVkx1rqPM8mEsBZxPAFAa9Nm6kLa7mQs6mRKTsRTFQaad7
privateKey: 5KX4T16FtxG9LvRJukA31TP9BKq3jYve3xQ3Px3ui8mzuJ7nUYE

**Comment by crazybits** [comment]
Slip48 is recommended

https://github.com/satoshilabs/slips/blob/master/slip-0048.md

**Comment by jcalfee** [comment]
@crazybits Sip48 does not cover role hierarchies ..  Where active is a child of owner.  Although role hierarchies can be completely ignored in key derivation if you want too.  What do you think about the role hierarchies in EOS?

It is a way to introduce a non-hardened path (without the Sip48 tick `'`) but with strings and no public chain code support.  So if you have the owner private you can create the active private and any more specific children of the active key.  That would allow string based roles to be created outside of cold storage that were sill recoverable without having to go back to cold storage and add it to the backup for example.

**Comment by jcalfee** [comment]
Please don't get carried away with this one.  I should mention though that the ECC math used for public / private chain codes did work for me when I used large numbers like arbitrary role names in EOS .. It is the spec that locks it down to numbers not the math .. It is actually just hashing the role ID to get the public or private key.  Using numbers allows for better discovery without an index and tends to drive people to go register and use well known roles though.  It is in my mind that strings can be in a modified BIP-0044/SLIP-0044 if it makes for a better use-case.

**Comment by c1pca** [comment]
As far as I know Ledger uses BIP-0044/SLIP-0044 ("m/44'/194'/0'/0/0").

**Comment by shikhars371** [comment]
> Thanks to your help, I could successfully derived my eos pub/priv key from my mnemonic 👍.
> Thank you very much!

hello sir, can you give me some reference on creating EOS active and owner keys by the help of mnemonic 12 words seed? please help me im stuck in this from past 4 days but no luck please help me
