### ISSUE TITLE
what  is this problem? Cannot find module 'eosjs-ecc' ,after sudo  npm  install  --unsafe-perm

### ISSUE THREAD

**Issue by jhomephper** [EOSIO/eosjs-ecc#8]
code:
const ecc = require('eosjs-ecc')

**Comment by jcalfee** [comment]
Not sure what your doing or trying to do.. If you installed the package as sudo are you then running node as sudo?  I never have to use sudo with npm .. ,

It says running as root (sudo) will switch this to false.. Looks like your turning it back on.

Unsafe-perm is poorly documented here at npmjs .. 
https://docs.npmjs.com/misc/config#unsafe-perm

One comment here added a boolean after that parameter:
`sudo npm install --unsafe-perm true PACKAGE_NAME`
ref: https://stackoverflow.com/questions/28763958/nodejs-unsafe-perm-not-working-on-package-json#28787942
